// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonAdd: typeof import('~icons/carbon/add')['default']
    CarbonClose: typeof import('~icons/carbon/close')['default']
    CarbonDelete: typeof import('~icons/carbon/delete')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPause: typeof import('~icons/carbon/pause')['default']
    CarbonPlay: typeof import('~icons/carbon/play')['default']
    CarbonReset: typeof import('~icons/carbon/reset')['default']
    CarbonSettings: typeof import('~icons/carbon/settings')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonTranslate: typeof import('~icons/carbon/translate')['default']
    InfoPanel: typeof import('./src/components/InfoPanel.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NElement: typeof import('naive-ui')['NElement']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NotificationsWarning: typeof import('./src/components/NotificationsWarning.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    OptionControls: typeof import('./src/components/OptionControls.vue')['default']
    PotatoProgress: typeof import('./src/components/PotatoProgress.vue')['default']
    PotatoSettings: typeof import('./src/components/PotatoSettings.vue')['default']
    PotatoTimer: typeof import('./src/components/PotatoTimer.vue')['default']
    ResetButton: typeof import('./src/components/ResetButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    ThemeSelector: typeof import('./src/components/ThemeSelector.vue')['default']
  }
}

export {}
